### ISSUE TITLE
Switch from FontAwesome webfonts to SVG

### ISSUE THREAD

**Issue by mikix** [edx/frontend-component-footer#21]
Currently, the footer component requires all downstream consumers to use FontAwesome (webfont version).

Ideally, it would not make any requirements on its consumers. But if it does, let's have it be for the SVG versions, which are much lighter.

But you could also just bundle in the social icons it needs? And avoid any dependency.

Related tickets:
https://github.com/edx/front-end-cookie-cutter-application/issues/178
https://github.com/edx/paragon/issues/347

**Comment by davidjoy** [comment]
@AlasdairSwan fixed this by removing the need for font awesome from the component entirely.  Closing!  (Note: The repo still technically depends on it so that the dev server/index.jsx file can show a nice example.
